### ISSUE TITLE
Issue generating BRF file 

### ISSUE THREAD

**Issue by mohammadstoneleighconsulting** [jianboqi/MART3D#2]
Hi there,

I hope you are doing well. I am grateful for your hard work in developing LessRT and PyLessSDK. I have recently been using the latest version of MART3D to create a LUT for inversion. However, I have encountered an issue when running the provided code (MART3D.py). The code only generates an "Irradiance.txt" file in the Results folder, with no other output (no _BRF.txt). Could you please help me address this problem?

Additionally, I am particularly interested in using only the grassland layers for my project, as I am working with mixed grassland dominated by clover, ryegrass, and brown top (ERECTOPHILE, PLANOPHILE LAD). I want to use a mesh similar to the one provided on the LESS website to conduct the simulation. However, I face difficulties integrating my custom mesh into the workflow and creating a LUT. Please guide me on how to add the mesh through the code and help me resolve this issue.

Thank you so much for your help.

Best regards,

**Comment by mohammadstoneleighconsulting** [comment]
Quick update. I managed to generate the BRF file. The issue was that I used the following path to write the data to disk.
my simulation\temp\forestplot091\Results\photontracing_0_05.

Removing the space (mysimulation\temp\forestplot091\Results\photontracing_0_05) fixed the issue.

**Comment by jianboqi** [comment]
Dear @mohammadstoneleighconsulting If you want to add your own mesh instead of the pre-generated ones in MART3D, I suggest to use PyLessSDK directly. With this SDK, you can set any parameters, such as adding your OBJ files, and adding new sensors, doing batch processings. You can find some examples about how to use the SDK inthe folder of PyLessSDK.  To facilitate the use of PyLessSDK, we recently also provided a new "Code Generation" feature in the GUI (Tools->Generate Python Code). With this new feature, when you create a simulation project with GUI, then you can generate a python script that creates this simulation, and then you can modify this code as you want, e.g., to loop some parameters to do batch-processing. The new version will be released soon, here, I provided a early-access version: https://drive.google.com/file/d/1lh0HPc8H2SSGDD7RbdB6wvfLupot8vah/view?usp=share_link
If you have any problem regarding the use of LESS, please do not hesitate to contact me.

**Comment by mohammadstoneleighconsulting** [comment]
Hi @jianboqi 
That is Awsome; thank you so much for your help! I downloaded the latest version of LESS using the link you provided. I tested the Generate Python Code command, and it is working great. I have started working on some code to generate a LUT.
Thank you very much for all the hard work you have put into this project.
